//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by d3d11.rc
//
#define ID_RENDER_DLL_NAME					5
#define IDR_EXTRA_WORLD_TWEAKS				102
#define IDR_SHADER_GLOBAL_HEADER			103
#define IDR_SHADER_OPTIMIZED_SURFACE_VS		104
#define IDR_SHADER_OPTIMIZED_SURFACE_PS		105
#define IDR_SHADER_SOLIDDRAWING_PS			106
#define IDR_SHADER_SOLIDDRAWING_VS			107
#define IDR_SHADER_TONEMAP_PS				108
#define IDR_SHADER_TONEMAP_VS				109
#define IDR_SHADER_SCREENFX_PS				110
#define IDR_SHADER_SCREENFX_VS				111
#define IDR_SHADER_CLEARSCREEN_PS			112
#define IDR_SHADER_CLEARSCREEN_VS			113
#define IDR_SHADER_FULLSCREEN_VIDEO_PS		114
#define IDR_SHADER_FULLSCREEN_VIDEO_VS		115
#define IDR_SHADER_MODEL_PS					116
#define IDR_SHADER_MODEL_VS					117
#define IDR_SHADER_WORLD_MODEL_PS			118
#define IDR_SHADER_WORLD_MODEL_VS			119
#define IDR_SHADER_SKY_WORLD_MODEL_PS		120
#define IDR_SHADER_SKY_WORLD_MODEL_VS		121
#define IDR_SHADER_SPRITE_PS				122
#define IDR_SHADER_SPRITE_VS				123
#define IDR_SHADER_PARTICLE_SYSTEM_PS		124
#define IDR_SHADER_PARTICLE_SYSTEM_VS		125
#define IDR_SHADER_CANVAS_PS				126
#define IDR_SHADER_CANVAS_VS				127
#define IDR_SHADER_POLYGRID_PS				128
#define IDR_SHADER_POLYGRID_VS				129
#define IDR_SHADER_LINE_SYSTEM_PS			130
#define IDR_SHADER_LINE_SYSTEM_VS			131
#define IDR_SHADER_PASSTHROUGH_PS			132
#define IDR_SHADER_PASSTHROUGH_VS			133
#define IDR_SHADER_BLOOM_EXTRACT_PS			134
#define IDR_SHADER_BLOOM_EXTRACT_VS			135
#define IDR_SHADER_BLOOM_BLUR_PS			136
#define IDR_SHADER_BLOOM_BLUR_VS			137
#define IDR_SHADER_BLOOM_COMBINE_PS			138
#define IDR_SHADER_BLOOM_COMBINE_VS			139
#define IDR_SHADER_OPTIMIZED_SURFACE_BAT_VS 140
#define IDR_SHADER_OPTIMIZED_SURFACE_BAT_PS 141
#define IDR_SHADER_SKY_PORTAL_PS			142
#define IDR_SHADER_SKY_PORTAL_VS			143
#define IDR_SHADER_MODEL_GS					144
#define IDR_SHADER_CANVAS_BAT_PS			145
#define IDR_SHADER_CANVAS_BAT_VS			146
#define IDR_SHADER_SPRITE_BAT_PS			147
#define IDR_SHADER_SPRITE_BAT_VS			148

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
